name: todo
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  get_storage: ^2.0.3
  get: ^4.3.8                   
  intl: ^0.17.0
  google_fonts: ^6.2.1
  date_picker_timeline: ^1.2.3
  sqflite: ^2.0.0+4
  flutter_svg: 2.0.9
  rxdart: ^0.27.2

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.4"
  flutter_lints: ^1.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/appicon.jpeg"
  min_sdk_android: 21



flutter:

  uses-material-design: true


  assets:
    - images/appicon.jpeg
    - images/person.jpeg
    - images/task.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
