name: smart_fridge_monitoring
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.0
  firebase_database: ^11.3.3
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.3.0
  syncfusion_flutter_gauges: ^24.1.41
  fl_chart: ^0.70.2
  uuid: ^4.5.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/loginpage.jpg
    - images/addfridge.jpg
    - images/addaccount.jpg
    - images/dashboard.jpg
  #   - images/a_dot_ham.jpeg